name: Update Docker Image

on:
  push:
    branches:
      - main

jobs:
  applying:
    name: Updating Docker Image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Building
        run: |
          docker image build -t docker-api-nodejs .

      - name: Tagging
        run: |
          docker image tag docker-api-nodejs rafaelvilarinho/docker-api-nodejs:latest
          docker image tag docker-api-nodejs rafaelvilarinho/docker-api-nodejs:${{ github.sha }}

      - name: Pushing to Docker Hub
        run: |
          docker image push -t rafaelvilarinho/docker-api-nodejs:latest
          docker image push -t rafaelvilarinho/docker-api-nodejs:${{ github.sha }}